=pod

=head1 NAME

Data::Range::Compare::Stream::Cookbook - Guide for Data::Range::Compare::Stream

=head1 DESCRIPTION

This Cook book acts as a documentation hub for Data::Range::Compare::Stream and its child modules.

=head2 Comparing Data Examples

This section provides examples on how to extend Data::Range::Compare::Stream to support various data types

=over 3

=item * IPV4 Example

Data::Range::Compare::Stream::Cookbook::COMPARE_IPV4

=item * DateTime Example

Data::Range::Compare::Stream::Cookbook::COMPARE_DateTime

=back

=head2 Range Iterator Examples

This section covers how to roll your own range iterator class, based on various data source types

=over 3

=item * The File Example

This example is on my ToDo list!

=item * The DBI Example

This example is on my ToDo list!

=back

=head2 Consolidate Iterator Examples

This section covers how to roll your own Consolidate iterator class, based on various data source types

=over 3

=item * The File Example

This example is on my ToDo list!

=item * The DBI Example

This example is on my ToDo list!

=item * Consolidating Contiguous ranges

This example is on my ToDo list!

=back

=head2 Compare Iterator Examples

This section covers how to use the Compare iterator in differnt ways

=over 3

=item * The Default Example

=item * The Layer Cake

=back

=head1 AUTHOR

Michael Shipper

=head1 Source-Forge Project

As of version 0.001 the Project has been moved to Source-Forge.net

L<Data Range Compare|https://sourceforge.net/projects/data-range-comp/>
L<https://sourceforge.net/projects/data-range-comp/>

=head1 COPYRIGHT

Copyright 2011 Michael Shipper.  All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut

