=pod

=head1 NAME

Data::Range::Compare::Stream::Cookbook - Guide for Data::Range::Compare::Stream

=head1 DESCRIPTION

This Cook book acts as a documentation hub for Data::Range::Compare::Stream and its child modules.

=head1 Comparing Data Examples

This section provides examples on how to extend Data::Range::Compare::Stream to support various data types


=head2 IPV4 Example See:

Data::Range::Compare::Stream::Cookbook::COMPARE_IPV4

=head2 DateTime Example See:

Data::Range::Compare::Stream::Cookbook::COMPARE_DateTime

=head1 Range Iterator Examples

This section covers how to roll your own range iterator class, based on various data source types

=head2 The File Example

This example is on my ToDo list!

=head2 The DBI Example

This example is on my ToDo list!

=head2 Consolidate Iterator Examples

This section covers how to roll your own Consolidate iterator class, based on various data source types

=head2 The File Example See:

This example is on my ToDo list!

=head2 The DBI Example See:

This example is on my ToDo list!

=head2 Consolidating Contiguous ranges

This example is on my ToDo list!

=head1 Compare Iterator Examples

This section covers how to use the Compare iterator in differnt ways

=head2 The Default Example See:

=head2 The Layer Cake See:

=head1 AUTHOR

Michael Shipper

=head1 Source-Forge Project

As of version 0.001 the Project has been moved to Source-Forge.net

L<Data Range Compare|https://sourceforge.net/projects/data-range-comp/>
L<https://sourceforge.net/projects/data-range-comp/>

=head1 COPYRIGHT

Copyright 2011 Michael Shipper.  All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut

