=pod

=head1 NAME

Data::Range::Compare::Stream::Cookbook - Guide for Data::Range::Compare::Stream

=head1 DESCRIPTION

This Cook book acts as a documentation hub for Data::Range::Compare::Stream and its child modules.

=head1 Comparing Data Examples

This section provides examples on how to extend Data::Range::Compare::Stream to support various data types

=head2 IPV4 Example See:

L<Data::Range::Compare::Stream::Cookbook::COMPARE_IPV4|Data::Range::Compare::Stream::Cookbook::COMPARE_IPV4>

=head2 DateTime Example See:

L<Data::Range::Compare::Stream::Cookbook::COMPARE_DateTime|Data::Range::Compare::Stream::Cookbook::COMPARE_DateTime>

=head1 Range Iterator Examples

This section covers how to create your own range iterator class, based on various data source types

=head2 The File Example

=head2 Consolidate Iterator Examples

The Adjacent Range example: L<Data::Range::Compare::Stream::Iterator::Consolidate::AdjacentAsc>

=head2 The File Example See:

=over 3

=item * Basic File example

If your raw fileis sorted with the start range value in ASC and the range end value DESC order 
then refer to the Base Iterator class.

L<Data::Range::Compare::Stream::Iterator::Base>

=item * Basic File Result Example

If you your raw file has no duplicates, overlaps and is sorted use this example:

L<Data::Range::Compare::Stream::Cookbook::FILE_RESULT_EXAMPLE>

=back

=head2 The Layer Cake:

Quick and dirty result filtering how to can be found here.

L<Data::Range::Compare::Stream::Iterator::Compare::LayerCake>>

=head1 AUTHOR

Michael Shipper

=head1 Source-Forge Project

As of version 0.001 the Project has been moved to Source-Forge.net

L<Data Range Compare|https://sourceforge.net/projects/data-range-comp/>

=head1 SVN Location

L<http://data-range-comp.svn.sourceforge.net/viewvc/data-range-comp/>

=head1 COPYRIGHT

Copyright 2011 Michael Shipper.  All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut

